USE [master]
GO

/****** Object:  Database [stock]    Script Date: 26/10/2021 18:38:14 ******/
CREATE DATABASE [stock] ON  PRIMARY 
( NAME = N'stock', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\stock.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'stock_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\stock_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [stock].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [stock] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [stock] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [stock] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [stock] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [stock] SET ARITHABORT OFF 
GO

ALTER DATABASE [stock] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [stock] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [stock] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [stock] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [stock] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [stock] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [stock] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [stock] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [stock] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [stock] SET  DISABLE_BROKER 
GO

ALTER DATABASE [stock] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [stock] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [stock] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [stock] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [stock] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [stock] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [stock] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [stock] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [stock] SET  MULTI_USER 
GO

ALTER DATABASE [stock] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [stock] SET DB_CHAINING OFF 
GO

ALTER DATABASE [stock] SET  READ_WRITE 
GO
USE [stock]
GO

/****** Object:  Table [dbo].[produits]    Script Date: 26/10/2021 18:39:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[produits](
	[N°produit] [int] NOT NULL,
	[libelle] [nchar](100) NULL,
	[stock] [int] NULL,
	[prix achat] [float] NULL,
	[prix vente] [float] NULL,
 CONSTRAINT [PK_produits] PRIMARY KEY CLUSTERED 
(
	[N°produit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [stock]
GO

/****** Object:  Table [dbo].[entree]    Script Date: 27/10/2021 15:27:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[entree](
	[N°entree] [int] IDENTITY(1,1) NOT NULL,
	[type piece] [nchar](30) NOT NULL,
	[n°piece] [nchar](20) NOT NULL,
	[date entree] [date] NOT NULL,
 CONSTRAINT [PK_entree] PRIMARY KEY CLUSTERED 
(
	[N°entree] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [stock]
GO

/****** Object:  Table [dbo].[dentree]    Script Date: 27/10/2021 15:28:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[dentree](
	[n°entree] [int] NOT NULL,
	[n°produit] [int] NOT NULL,
	[qte] [int] NOT NULL,
 CONSTRAINT [PK_dentree] PRIMARY KEY CLUSTERED 
(
	[n°entree] ASC,
	[n°produit] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[dentree]  WITH CHECK ADD  CONSTRAINT [FK_dentree_entree] FOREIGN KEY([n°entree])
REFERENCES [dbo].[entree] ([N°entree])
GO

ALTER TABLE [dbo].[dentree] CHECK CONSTRAINT [FK_dentree_entree]
GO

ALTER TABLE [dbo].[dentree]  WITH CHECK ADD  CONSTRAINT [FK_dentree_produits] FOREIGN KEY([n°produit])
REFERENCES [dbo].[produits] ([N°produit])
GO



